displayName=Collection Log Commands
author=mbsha
description=Adds ::log commands for locally cached Collection Log progress.
tags=collection,log,commands,clog
version=
plugins=com.collectionlogcommands.CollectionLogCommandsPlugin
build=standard
